import { MetadataRoute } from "next";
import { products } from "@/lib/products";

export default function sitemap(): MetadataRoute.Sitemap {
  const base = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";

  const productUrls = products.map((p) => ({
    url: `${base}/products/${p.slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.8,
  }));

  const blogUrls = [
    "best-notion-templates-freelancers-uae",
    "ai-prompts-for-freelancers",
    "freelance-systems-uae",
    "sop-templates-freelancers-online-business",
    "how-to-price-freelance-services-uae",
    "get-freelance-clients-uae",
    "freelance-proposal-tips-uae",
    "late-payment-freelance-uae",
    "client-onboarding-freelance-uae",
    "freelance-vs-salary-uae",
    "freelance-visa-uae",
    "freelance-tax-uae",
    "best-banks-freelancers-uae",
    "freelance-rate-calculator-uae",
    "best-freelance-platforms-uae",
    "freelance-contract-template-uae",
    "freelance-invoice-uae",
    "how-to-negotiate-freelance-rates-uae",
    "best-ai-tools-uae-freelancers",
    "notion-setup-guide-freelancers",
    "how-to-get-clients-linkedin-uae",
    "freelancer-burnout-uae",
    "how-to-become-freelancer-uae",
    "best-coworking-spaces-dubai",
    "how-to-get-international-clients-uae",
    "digital-nomad-visa-vs-freelance-visa-uae",
    "emaratax-registration-freelancers-uae",
    "how-much-do-uae-freelancers-earn",
    "how-to-scale-freelance-business-uae",
    "freelance-proposal-template-uae",
    "best-tools-freelancers-uae-2026",
    "how-to-build-freelance-portfolio-uae",
    "freelance-health-insurance-uae",
    "best-accounting-software-freelancers-uae",
    "how-to-use-chatgpt-freelancers-uae",
    "freelance-passive-income-uae",
    "freelance-linkedin-profile-uae",
    "how-to-fire-a-client-uae",
    "how-to-raise-rates-existing-clients-uae",
    "freelance-work-life-balance-uae",
    "freelance-developer-rates-uae",
    "how-to-write-freelance-bio-uae",
    "freelance-designer-rates-uae",
    "rakez-vs-ifza-freelance-license-uae",
    "uae-golden-visa-freelancers",
    "how-to-use-claude-ai-freelancers-uae",
    "get-referrals-freelance-uae",
    "freelance-financial-planning-uae",
    "freelance-marketing-rates-uae",
    "freelance-copywriter-rates-uae",
    "personal-brand-freelancer-uae",
    "freelance-consultant-rates-uae",
    "corporate-tax-uae-freelancers-2026",
    "best-coworking-spaces-abu-dhabi",
    "freelance-photographer-rates-uae",
    "freelance-video-editor-rates-uae",
    "best-virtual-offices-dubai",
    "freelance-accountant-uae",
    "freelance-project-manager-rates-uae",
    "how-to-start-online-business-uae",
    "client-communication-tips-freelancers-uae",
    "freelance-social-media-manager-rates-uae",
    "freelance-hr-consultant-uae",
    "how-to-get-uae-clients-from-abroad",
    "freelance-work-permit-vs-trade-license-uae",
    "how-to-price-yourself-as-freelancer-uae",
    "best-time-tracking-apps-freelancers-uae",
    "freelance-email-templates-uae",
    "freelance-niche-uae",
    "client-red-flags-uae",
    "freelance-rates-increase-strategy-uae",
    "freelance-dry-spells-uae",
    "uae-freelance-community-groups",
    "freelance-morning-routine-uae",
    "freelance-invoice-template-uae",
    "how-to-get-paid-faster-uae",
    "uae-freelance-tax-registration",
    "freelance-writer-rates-uae",
    "best-project-management-tools-freelancers",
    "dubai-free-zone-comparison-freelancers",
    "freelance-seo-consultant-rates-uae",
    "how-to-create-freelance-website-uae",
    "freelance-goals-setting-uae",
    "freelance-pr-consultant-rates-uae",
    "how-to-manage-multiple-clients-uae",
    "freelance-data-analyst-rates-uae",
    "freelance-ux-designer-rates-uae",
    "how-to-get-government-contracts-uae",
    "virtual-assistant-rates-uae",
    "freelance-trainer-rates-uae",
    "how-to-use-ai-write-proposals-uae",
    "freelance-translator-rates-uae",
    "freelance-architect-rates-uae",
    "how-to-sell-digital-products-uae",
    "freelance-legal-consultant-rates-uae",
    "freelance-cybersecurity-consultant-uae",
    "how-to-build-email-list-uae",
    "freelance-financial-advisor-rates-uae",
    "freelance-supply-chain-consultant-uae",
    "how-to-cold-email-clients-uae",
    "freelance-motion-designer-rates-uae",
    "freelance-event-planner-rates-uae",
    "how-to-use-notion-ai-freelancers-uae",
    "freelance-brand-strategist-rates-uae",
    "freelance-it-consultant-rates-uae",
    "how-to-use-gemini-ai-freelancers-uae",
    "freelance-recruitment-consultant-uae",
    "freelance-operations-consultant-uae",
    "how-to-build-freelance-agency-uae",
    "freelance-medical-writer-rates-uae",
    "freelance-real-estate-consultant-uae",
    "how-to-get-speaking-engagements-uae",
    "freelance-elearning-developer-rates-uae",
    "freelance-management-consultant-uae",
    "how-to-price-retainer-clients-uae",
    "freelance-graphic-designer-rates-uae",
    "freelance-digital-marketing-manager-uae",
    "how-to-handle-scope-creep-uae",
    "freelance-interior-design-rates-uae",
    "freelance-fashion-stylist-rates-uae",
    "how-to-use-linkedin-ads-freelancers-uae",
    "freelance-voiceover-artist-rates-uae",
    "freelance-3d-artist-rates-uae",
    "how-to-write-case-studies-uae",
    "freelance-content-creator-rates-uae",
    "freelance-web-developer-rates-uae",
    "how-to-set-freelance-boundaries-uae",
    "freelance-podcast-producer-rates-uae",
    "freelance-makeup-artist-rates-uae",
    "how-to-get-testimonials-uae",
    "freelance-animation-rates-uae",
    "freelance-life-coach-rates-uae",
    "how-to-build-freelance-waitlist-uae",
    "freelance-music-producer-rates-uae",
    "freelance-nutritionist-rates-uae",
    "how-to-invoice-international-clients-uae",
    "freelance-fitness-trainer-rates-uae",
    "freelance-business-coach-rates-uae",
    "how-to-find-cofounder-uae",
    "freelance-photographer-videographer-package-uae",
    "how-to-set-freelance-prices-uae",
    "freelance-social-media-strategist-rates-uae",
    "how-to-get-corporate-clients-uae",
    "freelance-data-scientist-rates-uae",
    "how-to-win-retainer-clients-uae",
    "freelance-training-development-rates-uae",
    "freelance-accountant-rates-uae",
    "how-to-use-upwork-uae",
    "freelance-public-speaker-rates-uae",
    "freelance-network-engineer-rates-uae",
    "freelance-salesforce-consultant-rates-uae",
    "how-to-build-passive-income-freelancer-uae",
    "freelance-cloud-architect-rates-uae",
    "how-to-manage-client-expectations-uae",
    "freelance-erp-consultant-rates-uae",
    "freelance-scrum-master-rates-uae",
    "how-to-write-freelance-proposal-uae",
    "freelance-excel-consultant-rates-uae",
    "freelance-blockchain-developer-rates-uae",
    "freelance-technical-writer-rates-uae",
    "how-to-get-first-freelance-client-uae",
    "freelance-product-manager-rates-uae",
    "how-to-use-fiverr-uae",
    "freelance-ai-engineer-rates-uae",
    "freelance-cybersecurity-rates-uae",
    "how-to-build-personal-brand-linkedin-uae",
    "freelance-devops-engineer-rates-uae",
    "freelance-sustainability-consultant-rates-uae",
    "how-to-build-a-freelance-team-uae",
    "freelance-tax-advisor-rates-uae",
    "freelance-immigration-consultant-rates-uae",
    "how-to-negotiate-contracts-freelance-uae",
    "freelance-wealth-manager-rates-uae",
    "freelance-change-management-consultant-rates-uae",
    "freelance-strategy-consultant-rates-uae",
    "how-to-build-email-list-freelancers-uae",
    "freelance-compliance-consultant-rates-uae",
    "how-to-use-ai-for-freelance-proposals-uae",
    "freelance-learning-development-consultant-rates-uae",
    "freelance-risk-management-consultant-rates-uae",
    "how-to-manage-freelance-finances-uae",
    "freelance-qa-engineer-rates-uae",
    "freelance-ios-developer-rates-uae",
    "freelance-android-developer-rates-uae",
    "how-to-deal-with-difficult-clients-uae",
    "freelance-fullstack-developer-rates-uae",
    "freelance-machine-learning-engineer-rates-uae",
    "how-to-use-notion-as-crm-uae",
    "freelance-frontend-developer-rates-uae",
    "how-to-ask-for-referrals-uae",
    "freelance-backend-developer-rates-uae",
  ].map((slug) => ({
    url: `${base}/blog/${slug}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/free`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.6 },
    { url: `${base}/about`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${base}/start`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/affiliates`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/bundle`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/guides`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.8 },
    { url: `${base}/faq`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/for/designers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/for/developers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/for/marketers`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/for/consultants`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/for/coaches`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    ...productUrls,
    ...blogUrls,
  ];
}
